# -*- coding: utf-8 -*-

import os


BASE_DIR = os.path.abspath(os.path.dirname(__file__))

REST_DURATION = 5 * 60
BLOCK_DURATION = 2 * 60

PPG_SAMPLE_RATE = 200
PPG_FIR_TAP_NUM = 200
PPG_FIR_CUTOFF = [0.5, 5.0]

BIOPAC_HEADER_LINES = 11
BIOPAC_MSEC_PER_SAMPLE_LINE_NUM = 2
BIOPAC_ECG_CHANNEL = 1
BIOPAC_SKIN_CONDUCTANCE_CHANNEL = 3